name: Deploy Web API to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Utiliza la versión adecuada de .NET para tu aplicación

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp110ej'  # Nombre de tu aplicación en Azure App Service
        slot-name: 'production'  # Nombre del slot si estás utilizando slots de implementación (opcional)
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
