name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with: 
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./PokemonReviewAppp.sln

    - name: Build
      run: dotnet build ./PokemonReviewAppp.sln --configuration Release --no-restore

    - name: Publish 
      run: dotnet publish ./PokemonReviewAppp.sln --configuration Release --no-build --output ./build

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<your-app-name>'
        slot-name: 'Production'
        package: './build'
