name: Build and Deploy to Azure

on:
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_NAME:  PokemonReviewAppp
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with: 
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./PokemonReviewAppp.sln

    - name: Build
      run: dotnet build ./PokemonReviewAppp.sln --configuration Release --no-restore

    - name: Publish 
      run: dotnet publish ./PokemonReviewAppp.sln --configuration Release --no-build --output  "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
        package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
